### ISSUE TITLE
supercontextmenu not IE  compatible

### ISSUE THREAD

**Issue by gprojects-ch** [pwnedgod/supercontextmenu#1]
Hello, I was testing the code in IE Version 11.0.9000.18861 and the contextmenu is not shown when right clicking. Open demopage in IE and you will see the error [https://www.jqueryscript.net/demo/Context-Menu-Plugin-jQuery-superContextMenu/](demo)
In my own application the contextmenu appears but the height of the element is too small. Looks like is missing the height. Pls can you check the compatibility for IE THX

**Comment by ezraisw** [comment]
Internet explorer is a bit problematic with flex boxes, but it is fixed now.
https://github.com/pwnedgod/supercontextmenu/commit/6f074f759a2f4b6caf05679b66f629f35e979ca9

**Comment by gprojects-ch** [comment]
Thanks @pwnedgod
